### PR TITLE
Add "Proxy/VPN check" and dummy urls

### PR DESCRIPTION
**Pull request by DemianX0**

### CODE REVIEW

**Comment by DemianX0** [comment]
Feature suggestion:  https://phabricator.wikimedia.org/T132892#5639101

**Comment by DemianX0** [comment]
The patch is rebased (updated) to the current version.

**Comment by prtksxna** [comment]
Thanks for the patch @AronMan5, I am sorry I took so long to merge it. Do note that this prototype is mostly for the team to discuss and experiment with ideas. Things here might not always make it to the final product.

**Comment by DemianX0** [comment]
Sure I know. However, parts might be copied, best to copy with the fix :-)

**Pull request merged**
